"""Research Ontology & Relation Rules Definition (Phase 0.4)."""

from researchforge.domain.graph.types import (
    Cardinality,
    RelationRule,
    ResearchNodeType,
    ResearchRelationType,
)

ONTOLOGY_RELATION_RULES: dict[ResearchRelationType, RelationRule] = {
    ResearchRelationType.CONTAINS: RelationRule(
        relation_type=ResearchRelationType.CONTAINS,
        valid_source_types={ResearchNodeType.PROJECT, ResearchNodeType.THREAD},
        valid_target_types={
            ResearchNodeType.QUESTION,
            ResearchNodeType.THREAD,
            ResearchNodeType.ARTIFACT,
            ResearchNodeType.EVIDENCE,
            ResearchNodeType.CLAIM,
            ResearchNodeType.EXPERIMENT,
        },
        cardinality=Cardinality.ONE_TO_MANY,
        description="Structural containment of research artifacts, questions, or threads within a project.",
        requires_provenance=True,
    ),
    ResearchRelationType.HAS_THREAD: RelationRule(
        relation_type=ResearchRelationType.HAS_THREAD,
        valid_source_types={ResearchNodeType.PROJECT},
        valid_target_types={ResearchNodeType.THREAD},
        cardinality=Cardinality.ONE_TO_MANY,
        description="Connects a project to its exploratory research threads.",
        requires_provenance=True,
    ),
    ResearchRelationType.ASKS: RelationRule(
        relation_type=ResearchRelationType.ASKS,
        valid_source_types={ResearchNodeType.PROJECT, ResearchNodeType.THREAD},
        valid_target_types={ResearchNodeType.QUESTION},
        cardinality=Cardinality.ONE_TO_MANY,
        description="Links a project or thread to its governing research question.",
        requires_provenance=True,
    ),
    ResearchRelationType.SOURCED_FROM: RelationRule(
        relation_type=ResearchRelationType.SOURCED_FROM,
        valid_source_types={
            ResearchNodeType.EVIDENCE,
            ResearchNodeType.EVIDENCE_FRAGMENT,
            ResearchNodeType.CLAIM,
        },
        valid_target_types={ResearchNodeType.SOURCE},
        cardinality=Cardinality.MANY_TO_ONE,
        description="Attribution link grounding evidence, fragments, or claims in an external literature source.",
        requires_provenance=True,
    ),
    ResearchRelationType.CONTAINS_FRAGMENT: RelationRule(
        relation_type=ResearchRelationType.CONTAINS_FRAGMENT,
        valid_source_types={ResearchNodeType.SOURCE, ResearchNodeType.EVIDENCE},
        valid_target_types={ResearchNodeType.EVIDENCE_FRAGMENT},
        cardinality=Cardinality.ONE_TO_MANY,
        description="Structural decomposition linking a source or evidence aggregate to granular fragments.",
        requires_provenance=True,
    ),
    ResearchRelationType.SUPPORTS: RelationRule(
        relation_type=ResearchRelationType.SUPPORTS,
        valid_source_types={
            ResearchNodeType.EVIDENCE,
            ResearchNodeType.EVIDENCE_FRAGMENT,
            ResearchNodeType.CONCLUSION,
        },
        valid_target_types={ResearchNodeType.CLAIM, ResearchNodeType.HYPOTHESIS},
        cardinality=Cardinality.MANY_TO_MANY,
        description="Epistemic validation asserting that an empirical observation supports a claim or hypothesis.",
        requires_provenance=True,
    ),
    ResearchRelationType.REFUTES: RelationRule(
        relation_type=ResearchRelationType.REFUTES,
        valid_source_types={
            ResearchNodeType.EVIDENCE,
            ResearchNodeType.EVIDENCE_FRAGMENT,
            ResearchNodeType.FALSIFICATION_EVALUATION,
        },
        valid_target_types={ResearchNodeType.CLAIM, ResearchNodeType.HYPOTHESIS},
        cardinality=Cardinality.MANY_TO_MANY,
        description="Empirical or statistical refutation rejecting a claim or falsifying a hypothesis.",
        requires_provenance=True,
    ),
    ResearchRelationType.QUALIFIES: RelationRule(
        relation_type=ResearchRelationType.QUALIFIES,
        valid_source_types={
            ResearchNodeType.EVIDENCE,
            ResearchNodeType.EVIDENCE_FRAGMENT,
            ResearchNodeType.CLAIM,
        },
        valid_target_types={ResearchNodeType.CLAIM, ResearchNodeType.HYPOTHESIS},
        cardinality=Cardinality.MANY_TO_MANY,
        description="Contextual or boundary condition qualification narrowing the scope of an assertion.",
        requires_provenance=True,
    ),
    ResearchRelationType.CONTRADICTS: RelationRule(
        relation_type=ResearchRelationType.CONTRADICTS,
        valid_source_types={ResearchNodeType.CLAIM, ResearchNodeType.CONTRADICTION},
        valid_target_types={ResearchNodeType.CLAIM},
        cardinality=Cardinality.MANY_TO_MANY,
        description="Identified conflict or opposing result between two scientific claims.",
        requires_provenance=True,
    ),
    ResearchRelationType.ADDRESSES: RelationRule(
        relation_type=ResearchRelationType.ADDRESSES,
        valid_source_types={
            ResearchNodeType.RESEARCH_GAP,
            ResearchNodeType.HYPOTHESIS,
            ResearchNodeType.EXPERIMENT,
        },
        valid_target_types={
            ResearchNodeType.QUESTION,
            ResearchNodeType.CONTRADICTION,
            ResearchNodeType.RESEARCH_GAP,
        },
        cardinality=Cardinality.MANY_TO_MANY,
        description="Targeting link indicating that a gap, hypothesis, or experiment addresses an open problem.",
        requires_provenance=True,
    ),
    ResearchRelationType.MOTIVATES: RelationRule(
        relation_type=ResearchRelationType.MOTIVATES,
        valid_source_types={
            ResearchNodeType.CONTRADICTION,
            ResearchNodeType.RESEARCH_GAP,
            ResearchNodeType.EVIDENCE,
        },
        valid_target_types={ResearchNodeType.RESEARCH_GAP, ResearchNodeType.HYPOTHESIS},
        cardinality=Cardinality.MANY_TO_MANY,
        description="Causal scientific rationale driving the formulation of a research gap or hypothesis candidate.",
        requires_provenance=True,
    ),
    ResearchRelationType.DERIVED_FROM: RelationRule(
        relation_type=ResearchRelationType.DERIVED_FROM,
        valid_source_types={
            ResearchNodeType.CLAIM,
            ResearchNodeType.RESEARCH_GAP,
            ResearchNodeType.HYPOTHESIS,
            ResearchNodeType.CONCLUSION,
        },
        valid_target_types={
            ResearchNodeType.SOURCE,
            ResearchNodeType.EVIDENCE,
            ResearchNodeType.RESEARCH_GAP,
            ResearchNodeType.HUMAN_DECISION,
        },
        cardinality=Cardinality.MANY_TO_MANY,
        description="Lineage derivation linking higher-order scientific syntheses to underlying constructs.",
        requires_provenance=True,
    ),
    ResearchRelationType.TESTS: RelationRule(
        relation_type=ResearchRelationType.TESTS,
        valid_source_types={ResearchNodeType.EXPERIMENT, ResearchNodeType.EXPERIMENT_DESIGN},
        valid_target_types={ResearchNodeType.HYPOTHESIS},
        cardinality=Cardinality.MANY_TO_ONE,
        description="Experimental operationalization designed to test and attempt to falsify a hypothesis.",
        requires_provenance=True,
    ),
    ResearchRelationType.TESTED_BY: RelationRule(
        relation_type=ResearchRelationType.TESTED_BY,
        valid_source_types={ResearchNodeType.HYPOTHESIS},
        valid_target_types={ResearchNodeType.EXPERIMENT, ResearchNodeType.EXPERIMENT_DESIGN},
        cardinality=Cardinality.ONE_TO_MANY,
        description="Semantic link from hypothesis to experiment design or operational experiment testing it.",
        requires_provenance=True,
    ),
    ResearchRelationType.HAS_DESIGN: RelationRule(
        relation_type=ResearchRelationType.HAS_DESIGN,
        valid_source_types={ResearchNodeType.EXPERIMENT},
        valid_target_types={ResearchNodeType.EXPERIMENT_DESIGN},
        cardinality=Cardinality.ONE_TO_ONE,
        description="Links an operational experiment to its declarative design specification.",
        requires_provenance=True,
    ),
    ResearchRelationType.HAS_PARAMETER_SPACE: RelationRule(
        relation_type=ResearchRelationType.HAS_PARAMETER_SPACE,
        valid_source_types={
            ResearchNodeType.EXPERIMENT_DESIGN,
            ResearchNodeType.EXPERIMENT,
            ResearchNodeType.EXPERIMENTAL_DESIGN_CANDIDATE,
        },
        valid_target_types={ResearchNodeType.PARAMETER_SPACE},
        cardinality=Cardinality.MANY_TO_ONE,
        description="Associates an experiment design or candidate design with its formal parameter space.",
        requires_provenance=True,
    ),
    ResearchRelationType.CONTAINS_PARAMETER: RelationRule(
        relation_type=ResearchRelationType.CONTAINS_PARAMETER,
        valid_source_types={ResearchNodeType.PARAMETER_SPACE},
        valid_target_types={ResearchNodeType.PARAMETER_DEFINITION},
        cardinality=Cardinality.ONE_TO_MANY,
        description="Structural containment linking a parameter space to parameter definitions.",
        requires_provenance=True,
    ),
    ResearchRelationType.CONSTRAINED_BY: RelationRule(
        relation_type=ResearchRelationType.CONSTRAINED_BY,
        valid_source_types={ResearchNodeType.PARAMETER_DEFINITION, ResearchNodeType.PARAMETER_SPACE},
        valid_target_types={ResearchNodeType.PARAMETER_CONSTRAINT},
        cardinality=Cardinality.MANY_TO_MANY,
        description="Associates a parameter definition or parameter space with validation constraints.",
        requires_provenance=True,
    ),
    ResearchRelationType.HAS_COMPUTATION_PLAN: RelationRule(
        relation_type=ResearchRelationType.HAS_COMPUTATION_PLAN,
        valid_source_types={ResearchNodeType.EXPERIMENT_DESIGN, ResearchNodeType.EXPERIMENT},
        valid_target_types={ResearchNodeType.COMPUTATION_PLAN},
        cardinality=Cardinality.ONE_TO_ONE,
        description="Associates an experiment design with its computational transformation plan.",
        requires_provenance=True,
    ),
    ResearchRelationType.SPECIFIES_EXECUTION: RelationRule(
        relation_type=ResearchRelationType.SPECIFIES_EXECUTION,
        valid_source_types={ResearchNodeType.COMPUTATION_PLAN, ResearchNodeType.EXPERIMENT_DESIGN},
        valid_target_types={ResearchNodeType.EXECUTION_SPECIFICATION},
        cardinality=Cardinality.ONE_TO_ONE,
        description="Links a computation plan or experiment design to its execution runtime specification.",
        requires_provenance=True,
    ),
    ResearchRelationType.SPECIFIES_DATASET: RelationRule(
        relation_type=ResearchRelationType.SPECIFIES_DATASET,
        valid_source_types={ResearchNodeType.COMPUTATION_PLAN, ResearchNodeType.EXPERIMENT_DESIGN},
        valid_target_types={ResearchNodeType.DATASET_SPECIFICATION},
        cardinality=Cardinality.ONE_TO_MANY,
        description="Links a computation plan to expected output dataset schemas and protocols.",
        requires_provenance=True,
    ),
    ResearchRelationType.SPECIFIES_ANALYSIS: RelationRule(
        relation_type=ResearchRelationType.SPECIFIES_ANALYSIS,
        valid_source_types={ResearchNodeType.COMPUTATION_PLAN, ResearchNodeType.EXPERIMENT_DESIGN},
        valid_target_types={ResearchNodeType.ANALYSIS_SPECIFICATION},
        cardinality=Cardinality.ONE_TO_MANY,
        description="Links a computation plan to statistical analysis specifications.",
        requires_provenance=True,
    ),
    ResearchRelationType.EXECUTED_AS: RelationRule(
        relation_type=ResearchRelationType.EXECUTED_AS,
        valid_source_types={
            ResearchNodeType.EXPERIMENT,
            ResearchNodeType.EXPERIMENT_DESIGN,
            ResearchNodeType.EXECUTION_SPECIFICATION,
        },
        valid_target_types={ResearchNodeType.EXPERIMENT_RUN},
        cardinality=Cardinality.ONE_TO_MANY,
        description="Execution tracking linking an experiment or execution specification to a concrete run instance.",
        requires_provenance=True,
    ),
    ResearchRelationType.PRODUCES: RelationRule(
        relation_type=ResearchRelationType.PRODUCES,
        valid_source_types={
            ResearchNodeType.EXPERIMENT,
            ResearchNodeType.EXPERIMENT_RUN,
            ResearchNodeType.STATISTICAL_ANALYSIS,
        },
        valid_target_types={
            ResearchNodeType.EXPERIMENT_RUN,
            ResearchNodeType.ARTIFACT,
            ResearchNodeType.FALSIFICATION_EVALUATION,
        },
        cardinality=Cardinality.ONE_TO_MANY,
        description=(
            "Execution output generation linking an experiment or run to its produced artifacts and evaluations."
        ),
        requires_provenance=True,
    ),
    ResearchRelationType.PRODUCES_DATASET: RelationRule(
        relation_type=ResearchRelationType.PRODUCES_DATASET,
        valid_source_types={ResearchNodeType.EXPERIMENT_RUN},
        valid_target_types={ResearchNodeType.DATASET_SPECIFICATION, ResearchNodeType.ARTIFACT},
        cardinality=Cardinality.ONE_TO_MANY,
        description="Data generation link from experiment run to produced datasets or artifact files.",
        requires_provenance=True,
    ),
    ResearchRelationType.ANALYSIS_CONSUMES: RelationRule(
        relation_type=ResearchRelationType.ANALYSIS_CONSUMES,
        valid_source_types={ResearchNodeType.STATISTICAL_ANALYSIS, ResearchNodeType.ANALYSIS_SPECIFICATION},
        valid_target_types={ResearchNodeType.DATASET_SPECIFICATION, ResearchNodeType.ARTIFACT},
        cardinality=Cardinality.MANY_TO_MANY,
        description="Data dependency link indicating that an analysis consumes a specific dataset or artifact.",
        requires_provenance=True,
    ),
    ResearchRelationType.INFORMS_FALSIFICATION: RelationRule(
        relation_type=ResearchRelationType.INFORMS_FALSIFICATION,
        valid_source_types={ResearchNodeType.STATISTICAL_ANALYSIS, ResearchNodeType.ANALYSIS_SPECIFICATION},
        valid_target_types={ResearchNodeType.FALSIFICATION_EVALUATION},
        cardinality=Cardinality.MANY_TO_MANY,
        description="Feeds statistical analysis findings into a formal falsification evaluation.",
        requires_provenance=True,
    ),
    ResearchRelationType.EVALUATES: RelationRule(
        relation_type=ResearchRelationType.EVALUATES,
        valid_source_types={ResearchNodeType.FALSIFICATION_EVALUATION},
        valid_target_types={
            ResearchNodeType.HYPOTHESIS,
            ResearchNodeType.EXPERIMENT_RUN,
            ResearchNodeType.EXPERIMENT_DESIGN,
        },
        cardinality=Cardinality.MANY_TO_MANY,
        description="Statistical evaluation assessing falsification criteria against experimental run results.",
        requires_provenance=True,
    ),
    ResearchRelationType.INFORMS: RelationRule(
        relation_type=ResearchRelationType.INFORMS,
        valid_source_types={
            ResearchNodeType.FALSIFICATION_EVALUATION,
            ResearchNodeType.EVIDENCE,
            ResearchNodeType.CLAIM,
            ResearchNodeType.STATISTICAL_ANALYSIS,
        },
        valid_target_types={ResearchNodeType.HUMAN_DECISION},
        cardinality=Cardinality.MANY_TO_ONE,
        description="Epistemic substrate informing human gatekeeper decisions.",
        requires_provenance=True,
    ),
    ResearchRelationType.ESTABLISHES: RelationRule(
        relation_type=ResearchRelationType.ESTABLISHES,
        valid_source_types={ResearchNodeType.HUMAN_DECISION},
        valid_target_types={
            ResearchNodeType.CONCLUSION,
            ResearchNodeType.EXPERIMENT_DESIGN,
            ResearchNodeType.EXPERIMENT,
        },
        cardinality=Cardinality.ONE_TO_ONE,
        description=(
            "Cryptographic human authorization establishing a verified scientific conclusion or authoritative design."
        ),
        requires_provenance=True,
    ),
    ResearchRelationType.MATERIALIZES_AS: RelationRule(
        relation_type=ResearchRelationType.MATERIALIZES_AS,
        valid_source_types={
            ResearchNodeType.CONCLUSION,
            ResearchNodeType.EXPERIMENT_RUN,
            ResearchNodeType.PROJECT,
            ResearchNodeType.STATISTICAL_ANALYSIS,
        },
        valid_target_types={ResearchNodeType.ARTIFACT},
        cardinality=Cardinality.ONE_TO_MANY,
        description="Publication and artifact generation converting conclusions and runs into immutable bundles.",
        requires_provenance=True,
    ),
    ResearchRelationType.HAS_ASSUMPTION: RelationRule(
        relation_type=ResearchRelationType.HAS_ASSUMPTION,
        valid_source_types={ResearchNodeType.SCIENTIFIC_MODEL, ResearchNodeType.HYPOTHESIS},
        valid_target_types={ResearchNodeType.ASSUMPTION},
        cardinality=Cardinality.ONE_TO_MANY,
        description="Explicit assumption underlying a scientific model or hypothesis.",
        requires_provenance=True,
    ),
    ResearchRelationType.USED_BY: RelationRule(
        relation_type=ResearchRelationType.USED_BY,
        valid_source_types={ResearchNodeType.SCIENTIFIC_MODEL},
        valid_target_types={ResearchNodeType.EXPERIMENT, ResearchNodeType.EXPERIMENT_DESIGN},
        cardinality=Cardinality.ONE_TO_MANY,
        description="Links a scientific model to the experiments that use it.",
        requires_provenance=True,
    ),
    ResearchRelationType.COMPARES: RelationRule(
        relation_type=ResearchRelationType.COMPARES,
        valid_source_types={ResearchNodeType.MODEL_COMPARISON},
        valid_target_types={ResearchNodeType.SCIENTIFIC_MODEL},
        cardinality=Cardinality.MANY_TO_MANY,
        description="Links a model comparison to the models it compares.",
        requires_provenance=True,
    ),
    ResearchRelationType.GENERATES_EVIDENCE_FOR: RelationRule(
        relation_type=ResearchRelationType.GENERATES_EVIDENCE_FOR,
        valid_source_types={ResearchNodeType.MODEL_COMPARISON, ResearchNodeType.STATISTICAL_ANALYSIS},
        valid_target_types={ResearchNodeType.FALSIFICATION_EVALUATION},
        cardinality=Cardinality.MANY_TO_MANY,
        description="Model comparison or analysis generates evidence for falsification evaluation.",
        requires_provenance=True,
    ),
    ResearchRelationType.INFORMS_DESIGN: RelationRule(
        relation_type=ResearchRelationType.INFORMS_DESIGN,
        valid_source_types={
            ResearchNodeType.MODEL_COMPARISON,
            ResearchNodeType.SENSITIVITY_STUDY,
            ResearchNodeType.HYPOTHESIS,
            ResearchNodeType.QUESTION,
        },
        valid_target_types={ResearchNodeType.EXPERIMENTAL_DESIGN_CANDIDATE},
        cardinality=Cardinality.MANY_TO_MANY,
        description=(
            "Links model comparisons, sensitivity studies, or research questions to candidate experimental designs."
        ),
        requires_provenance=True,
    ),
    ResearchRelationType.EVALUATES_CANDIDATE: RelationRule(
        relation_type=ResearchRelationType.EVALUATES_CANDIDATE,
        valid_source_types={ResearchNodeType.CANDIDATE_DESIGN_EVALUATION},
        valid_target_types={ResearchNodeType.EXPERIMENTAL_DESIGN_CANDIDATE},
        cardinality=Cardinality.ONE_TO_ONE,
        description="Links a formal multi-metric evaluation to its subject candidate design.",
        requires_provenance=True,
    ),
    ResearchRelationType.PROMOTED_TO: RelationRule(
        relation_type=ResearchRelationType.PROMOTED_TO,
        valid_source_types={ResearchNodeType.EXPERIMENTAL_DESIGN_CANDIDATE},
        valid_target_types={ResearchNodeType.EXPERIMENT_DESIGN, ResearchNodeType.EXPERIMENT},
        cardinality=Cardinality.ONE_TO_ONE,
        description=(
            "Records the human-authorized promotion of a candidate design to an authoritative experiment design."
        ),
        requires_provenance=True,
    ),
    ResearchRelationType.TARGETS_OBSERVABLE: RelationRule(
        relation_type=ResearchRelationType.TARGETS_OBSERVABLE,
        valid_source_types={
            ResearchNodeType.EXPERIMENTAL_DESIGN_CANDIDATE,
            ResearchNodeType.EXPERIMENT_DESIGN,
        },
        valid_target_types={
            ResearchNodeType.OBSERVABLE_DEFINITION,
            ResearchNodeType.CLAIM,
            ResearchNodeType.HYPOTHESIS,
        },
        cardinality=Cardinality.MANY_TO_MANY,
        description="Specifies target observables intended to discriminate models or test hypotheses.",
        requires_provenance=True,
    ),
    ResearchRelationType.INCLUDES_CANDIDATE: RelationRule(
        relation_type=ResearchRelationType.INCLUDES_CANDIDATE,
        valid_source_types={ResearchNodeType.PARETO_CANDIDATE_SET},
        valid_target_types={ResearchNodeType.EXPERIMENTAL_DESIGN_CANDIDATE},
        cardinality=Cardinality.ONE_TO_MANY,
        description="Associates a Pareto non-dominated set with its member candidate designs.",
        requires_provenance=True,
    ),
}


def get_relation_rule(relation_type: ResearchRelationType) -> RelationRule:
    """Retrieve ontological rule for a relation type."""
    if relation_type not in ONTOLOGY_RELATION_RULES:
        raise KeyError(f"Unknown relation type {relation_type} not in ontology.")
    return ONTOLOGY_RELATION_RULES[relation_type]
