"""ResearchForge persistence layer."""

from researchforge.persistence.adapters.graph import GraphPersistenceAdapter
from researchforge.persistence.database import DatabaseManager, get_db_manager, init_db
from researchforge.persistence.models import (
    AnalysisRecord,
    ArtifactRecord,
    Base,
    ConclusionRecord,
    EvidenceRecord,
    ExperimentRecord,
    FalsificationRecord,
    GapRecord,
    HumanDecisionRecord,
    HypothesisRecord,
    IdempotencyRecord,
    ProjectRecord,
    ProvenanceEventRecord,
    QuestionRecord,
    RunRecord,
    ThreadRecord,
)
from researchforge.persistence.repositories import (
    ArtifactRepository,
    ConclusionRepository,
    EvidenceRepository,
    ExperimentRepository,
    FalsificationRepository,
    GapRepository,
    HumanDecisionRepository,
    HypothesisRepository,
    IdempotencyRepository,
    ProjectRepository,
    ProvenanceRepository,
    QuestionRepository,
    RunRepository,
    ThreadRepository,
)
from researchforge.persistence.unit_of_work import UnitOfWork

__all__ = [
    "AnalysisRecord",
    "ArtifactRecord",
    "ArtifactRepository",
    "Base",
    "ConclusionRecord",
    "ConclusionRepository",
    "DatabaseManager",
    "EvidenceRecord",
    "EvidenceRepository",
    "ExperimentRecord",
    "ExperimentRepository",
    "FalsificationRecord",
    "FalsificationRepository",
    "GapRecord",
    "GapRepository",
    "GraphPersistenceAdapter",
    "HumanDecisionRecord",
    "HumanDecisionRepository",
    "HypothesisRecord",
    "HypothesisRepository",
    "IdempotencyRecord",
    "IdempotencyRepository",
    "ProjectRecord",
    "ProjectRepository",
    "ProvenanceEventRecord",
    "ProvenanceRepository",
    "QuestionRecord",
    "QuestionRepository",
    "RunRecord",
    "RunRepository",
    "ThreadRecord",
    "ThreadRepository",
    "UnitOfWork",
    "get_db_manager",
    "init_db",
]
