"""Typed provenance event registry (Section 15)."""

from enum import StrEnum


class ProvenanceEventType(StrEnum):
    """The complete, formal registry of tracked research provenance events."""

    # Project & Question
    PROJECT_CREATED = "PROJECT_CREATED"
    QUESTION_DEFINED = "QUESTION_DEFINED"

    # Literature & Evidence
    SOURCE_RETRIEVED = "SOURCE_RETRIEVED"
    SOURCE_INGESTED = "SOURCE_INGESTED"
    DOCUMENT_NORMALIZED = "DOCUMENT_NORMALIZED"
    EVIDENCE_EXTRACTED = "EVIDENCE_EXTRACTED"
    CLAIM_CREATED = "CLAIM_CREATED"
    CLAIM_BOUND = "CLAIM_BOUND"
    CONTRADICTION_IDENTIFIED = "CONTRADICTION_IDENTIFIED"
    GAP_IDENTIFIED = "GAP_IDENTIFIED"

    # Hypothesis & Critique
    HYPOTHESIS_FORMED = "HYPOTHESIS_FORMED"
    HYPOTHESIS_CREATED = "HYPOTHESIS_CREATED"
    HYPOTHESIS_GENERATED = "HYPOTHESIS_GENERATED"
    HYPOTHESIS_SUBMITTED = "HYPOTHESIS_SUBMITTED"
    HYPOTHESIS_CRITIQUED = "HYPOTHESIS_CRITIQUED"

    # Experiment & Execution
    EXPERIMENT_DESIGNED = "EXPERIMENT_DESIGNED"
    EXPERIMENT_EXECUTED = "EXPERIMENT_EXECUTED"
    EXECUTION_APPROVED = "EXECUTION_APPROVED"
    RUN_CREATED = "RUN_CREATED"
    RUN_STARTED = "RUN_STARTED"
    RUN_COMPLETED = "RUN_COMPLETED"
    RUN_FAILED = "RUN_FAILED"
    RUN_CANCELED = "RUN_CANCELED"
    RESULTS_RECORDED = "RESULTS_RECORDED"

    # Evaluation & Human Review
    FALSIFICATION_EVALUATED = "FALSIFICATION_EVALUATED"
    HUMAN_REVIEW_STARTED = "HUMAN_REVIEW_STARTED"
    DECISION_ACCEPTED = "DECISION_ACCEPTED"
    DECISION_REJECTED = "DECISION_REJECTED"
    CONCLUSION_ACCEPTED = "CONCLUSION_ACCEPTED"

    # Artifacts & Checkpoints
    ARTIFACT_GENERATED = "ARTIFACT_GENERATED"
    ARTIFACT_VERIFIED = "ARTIFACT_VERIFIED"
    ARTIFACT_INVALIDATED = "ARTIFACT_INVALIDATED"
    ARTIFACT_SUPERSEDED = "ARTIFACT_SUPERSEDED"
    CHECKPOINT_COMMITTED = "CHECKPOINT_COMMITTED"
    PROVENANCE_VERIFIED = "PROVENANCE_VERIFIED"
    STATE_TRANSITIONED = "STATE_TRANSITIONED"
